function [c] = coefficients_quartic(theta0,theta1,thetaf,t1,tf)
% Calculates the coefficients of the quartic polynomial
% Input     Type        Description
% theta0    1x1 double  start angle position
% theta1    1x1 double  via angle position
% thetaf    1x1 double  final angle position
% t1        1x1 double  via time
% tf        1x1 double  finish time
% Output    Type        Description
% c         5x1 double  coefficients of quartic polynomial
c = zeros(5,1);
M = [0, 0, 0, 0, 1;...
     0, 0, 0, 1, 0;...
     tf^4, tf^3, tf^2 , tf, 1;...
     4*tf^3, 3*tf^2, 2*tf, 1, 0;...
     t1^4, t1^3, t1^2 , t1, 1];
x = [theta0;...
     0;...
     thetaf;...
     0;...
     theta1];
c = M^-1*x;
end

