function [c] = coefficients_quintic(theta0,thetaf,tf)
% Calculates the coefficients of the quintic polynomial
% Input     Type        Description
% theta0    1x1 double  start angle position
% thetaf    1x1 double  final angle position
% tf        1x1 double  finish time
% Output    Type        Description
% c         6x1 double  coefficients of quintic polynomial
c = zeros(6,1);
M = [0, 0, 0, 0, 0, 1;...
     0, 0, 0, 0, 1, 0;...
     0, 0, 0, 2, 0, 0;...
     tf^5, tf^4, tf^3, tf^2 , tf, 1;...
     5*tf^4, 4*tf^3, 3*tf^2, 2*tf, 1, 0;...
     20*tf^3, 12*tf^2, 6*tf, 2, 0, 0];
x = [theta0;...
     0;...
     0;...
     thetaf;...
     0;...
     0];
c = M^-1*x;
end

