function [c,te] = cd_refpoly_vmax(vmax, x0, xs)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
te = 15*xs/8/vmax;
c = [65536*vmax*vmax*vmax*vmax*vmax/xs/xs/xs/xs/253125;...
     -4096*vmax*vmax*vmax*vmax/xs/xs/xs/3375;...
     1024*vmax*vmax*vmax/xs/xs/675;...
     0;...
     0;...
     x0];
end

