function cff = cd_refpoly_ff(c, k, T, Tt, kr, Ti)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
kkr1 = 1/k/kr + 1;
cff = [c(6);...
       c(5) + 5*Ti*c(6)*kkr1;...
       c(4) + 4*Ti*c(5)*kkr1 + 20*Ti*c(6)*(T+Tt)/k/kr;...
       c(3) + 3*Ti*c(4)*kkr1 + 12*Ti*c(5)*(T+Tt)/k/kr + 60*T*Ti*Tt*c(6)/k/kr;...
       c(2) + 2*Ti*c(3)*kkr1 +  6*Ti*c(4)*(T+Tt)/k/kr + 24*T*Ti*Tt*c(5)/k/kr;...
       c(1) +   Ti*c(2)*kkr1 +  2*Ti*c(3)*(T+Tt)/k/kr +  6*T*Ti*Tt*c(4)/k/kr];
end

